//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CadastroEmpresaLibrary.ServicoCNPJ {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsConsultaSoap", Namespace="http://sped.fazenda.gov.br/")]
    public partial class WsConsulta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarInformacoesCadastraisOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarInformacoesIntermediarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarInformacoesPatrocinadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarListaEFinanceiraOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarInformacoesMovimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarInformacoesRerctOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsConsulta() {
            this.Url = global::CadastroEmpresaLibrary.Properties.Settings.Default.CadastroEmpresaLibrary_br_gov_rfb_sped_WsConsulta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarInformacoesCadastraisCompletedEventHandler ConsultarInformacoesCadastraisCompleted;
        
        /// <remarks/>
        public event ConsultarInformacoesIntermediarioCompletedEventHandler ConsultarInformacoesIntermediarioCompleted;
        
        /// <remarks/>
        public event ConsultarInformacoesPatrocinadoCompletedEventHandler ConsultarInformacoesPatrocinadoCompleted;
        
        /// <remarks/>
        public event ConsultarListaEFinanceiraCompletedEventHandler ConsultarListaEFinanceiraCompleted;
        
        /// <remarks/>
        public event ConsultarInformacoesMovimentoCompletedEventHandler ConsultarInformacoesMovimentoCompleted;
        
        /// <remarks/>
        public event ConsultarInformacoesRerctCompletedEventHandler ConsultarInformacoesRerctCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultarInformacoesCadastrais", RequestNamespace="http://sped.fazenda.gov.br/", ResponseNamespace="http://sped.fazenda.gov.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultarInformacoesCadastrais(string cnpj) {
            object[] results = this.Invoke("ConsultarInformacoesCadastrais", new object[] {
                        cnpj});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarInformacoesCadastraisAsync(string cnpj) {
            this.ConsultarInformacoesCadastraisAsync(cnpj, null);
        }
        
        /// <remarks/>
        public void ConsultarInformacoesCadastraisAsync(string cnpj, object userState) {
            if ((this.ConsultarInformacoesCadastraisOperationCompleted == null)) {
                this.ConsultarInformacoesCadastraisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarInformacoesCadastraisOperationCompleted);
            }
            this.InvokeAsync("ConsultarInformacoesCadastrais", new object[] {
                        cnpj}, this.ConsultarInformacoesCadastraisOperationCompleted, userState);
        }
        
        private void OnConsultarInformacoesCadastraisOperationCompleted(object arg) {
            if ((this.ConsultarInformacoesCadastraisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarInformacoesCadastraisCompleted(this, new ConsultarInformacoesCadastraisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultarInformacoesIntermediario", RequestNamespace="http://sped.fazenda.gov.br/", ResponseNamespace="http://sped.fazenda.gov.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultarInformacoesIntermediario(string cnpj, string GINN, string TipoNI, string NumeroIdentificacao) {
            object[] results = this.Invoke("ConsultarInformacoesIntermediario", new object[] {
                        cnpj,
                        GINN,
                        TipoNI,
                        NumeroIdentificacao});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarInformacoesIntermediarioAsync(string cnpj, string GINN, string TipoNI, string NumeroIdentificacao) {
            this.ConsultarInformacoesIntermediarioAsync(cnpj, GINN, TipoNI, NumeroIdentificacao, null);
        }
        
        /// <remarks/>
        public void ConsultarInformacoesIntermediarioAsync(string cnpj, string GINN, string TipoNI, string NumeroIdentificacao, object userState) {
            if ((this.ConsultarInformacoesIntermediarioOperationCompleted == null)) {
                this.ConsultarInformacoesIntermediarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarInformacoesIntermediarioOperationCompleted);
            }
            this.InvokeAsync("ConsultarInformacoesIntermediario", new object[] {
                        cnpj,
                        GINN,
                        TipoNI,
                        NumeroIdentificacao}, this.ConsultarInformacoesIntermediarioOperationCompleted, userState);
        }
        
        private void OnConsultarInformacoesIntermediarioOperationCompleted(object arg) {
            if ((this.ConsultarInformacoesIntermediarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarInformacoesIntermediarioCompleted(this, new ConsultarInformacoesIntermediarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultarInformacoesPatrocinado", RequestNamespace="http://sped.fazenda.gov.br/", ResponseNamespace="http://sped.fazenda.gov.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultarInformacoesPatrocinado(string cnpj, string GINN, string NumeroIdentificacao) {
            object[] results = this.Invoke("ConsultarInformacoesPatrocinado", new object[] {
                        cnpj,
                        GINN,
                        NumeroIdentificacao});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarInformacoesPatrocinadoAsync(string cnpj, string GINN, string NumeroIdentificacao) {
            this.ConsultarInformacoesPatrocinadoAsync(cnpj, GINN, NumeroIdentificacao, null);
        }
        
        /// <remarks/>
        public void ConsultarInformacoesPatrocinadoAsync(string cnpj, string GINN, string NumeroIdentificacao, object userState) {
            if ((this.ConsultarInformacoesPatrocinadoOperationCompleted == null)) {
                this.ConsultarInformacoesPatrocinadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarInformacoesPatrocinadoOperationCompleted);
            }
            this.InvokeAsync("ConsultarInformacoesPatrocinado", new object[] {
                        cnpj,
                        GINN,
                        NumeroIdentificacao}, this.ConsultarInformacoesPatrocinadoOperationCompleted, userState);
        }
        
        private void OnConsultarInformacoesPatrocinadoOperationCompleted(object arg) {
            if ((this.ConsultarInformacoesPatrocinadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarInformacoesPatrocinadoCompleted(this, new ConsultarInformacoesPatrocinadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultarListaEFinanceira", RequestNamespace="http://sped.fazenda.gov.br/", ResponseNamespace="http://sped.fazenda.gov.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultarListaEFinanceira(string cnpj, int situacaoEFinanceira, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> dataInicio, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> dataFim) {
            object[] results = this.Invoke("ConsultarListaEFinanceira", new object[] {
                        cnpj,
                        situacaoEFinanceira,
                        dataInicio,
                        dataFim});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarListaEFinanceiraAsync(string cnpj, int situacaoEFinanceira, System.Nullable<System.DateTime> dataInicio, System.Nullable<System.DateTime> dataFim) {
            this.ConsultarListaEFinanceiraAsync(cnpj, situacaoEFinanceira, dataInicio, dataFim, null);
        }
        
        /// <remarks/>
        public void ConsultarListaEFinanceiraAsync(string cnpj, int situacaoEFinanceira, System.Nullable<System.DateTime> dataInicio, System.Nullable<System.DateTime> dataFim, object userState) {
            if ((this.ConsultarListaEFinanceiraOperationCompleted == null)) {
                this.ConsultarListaEFinanceiraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarListaEFinanceiraOperationCompleted);
            }
            this.InvokeAsync("ConsultarListaEFinanceira", new object[] {
                        cnpj,
                        situacaoEFinanceira,
                        dataInicio,
                        dataFim}, this.ConsultarListaEFinanceiraOperationCompleted, userState);
        }
        
        private void OnConsultarListaEFinanceiraOperationCompleted(object arg) {
            if ((this.ConsultarListaEFinanceiraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarListaEFinanceiraCompleted(this, new ConsultarListaEFinanceiraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultarInformacoesMovimento", RequestNamespace="http://sped.fazenda.gov.br/", ResponseNamespace="http://sped.fazenda.gov.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultarInformacoesMovimento(string cnpj, string situacaoInformacao, string anoMesInicioVigencia, string anoMesTerminoVigencia, string tipoMovimento, string tipoIdentificacao, string identificacao) {
            object[] results = this.Invoke("ConsultarInformacoesMovimento", new object[] {
                        cnpj,
                        situacaoInformacao,
                        anoMesInicioVigencia,
                        anoMesTerminoVigencia,
                        tipoMovimento,
                        tipoIdentificacao,
                        identificacao});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarInformacoesMovimentoAsync(string cnpj, string situacaoInformacao, string anoMesInicioVigencia, string anoMesTerminoVigencia, string tipoMovimento, string tipoIdentificacao, string identificacao) {
            this.ConsultarInformacoesMovimentoAsync(cnpj, situacaoInformacao, anoMesInicioVigencia, anoMesTerminoVigencia, tipoMovimento, tipoIdentificacao, identificacao, null);
        }
        
        /// <remarks/>
        public void ConsultarInformacoesMovimentoAsync(string cnpj, string situacaoInformacao, string anoMesInicioVigencia, string anoMesTerminoVigencia, string tipoMovimento, string tipoIdentificacao, string identificacao, object userState) {
            if ((this.ConsultarInformacoesMovimentoOperationCompleted == null)) {
                this.ConsultarInformacoesMovimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarInformacoesMovimentoOperationCompleted);
            }
            this.InvokeAsync("ConsultarInformacoesMovimento", new object[] {
                        cnpj,
                        situacaoInformacao,
                        anoMesInicioVigencia,
                        anoMesTerminoVigencia,
                        tipoMovimento,
                        tipoIdentificacao,
                        identificacao}, this.ConsultarInformacoesMovimentoOperationCompleted, userState);
        }
        
        private void OnConsultarInformacoesMovimentoOperationCompleted(object arg) {
            if ((this.ConsultarInformacoesMovimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarInformacoesMovimentoCompleted(this, new ConsultarInformacoesMovimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultarInformacoesRerct", RequestNamespace="http://sped.fazenda.gov.br/", ResponseNamespace="http://sped.fazenda.gov.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultarInformacoesRerct(int idEventoRerct, string situacaoInformacao, string numeroRecibo, string cnpjDeclarante, string tipoInscricaoDeclarado, string inscricaoDeclarado, string tipoInscricaoTitular, string inscricaoTitular, string cpfBeneficiarioFinal) {
            object[] results = this.Invoke("ConsultarInformacoesRerct", new object[] {
                        idEventoRerct,
                        situacaoInformacao,
                        numeroRecibo,
                        cnpjDeclarante,
                        tipoInscricaoDeclarado,
                        inscricaoDeclarado,
                        tipoInscricaoTitular,
                        inscricaoTitular,
                        cpfBeneficiarioFinal});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarInformacoesRerctAsync(int idEventoRerct, string situacaoInformacao, string numeroRecibo, string cnpjDeclarante, string tipoInscricaoDeclarado, string inscricaoDeclarado, string tipoInscricaoTitular, string inscricaoTitular, string cpfBeneficiarioFinal) {
            this.ConsultarInformacoesRerctAsync(idEventoRerct, situacaoInformacao, numeroRecibo, cnpjDeclarante, tipoInscricaoDeclarado, inscricaoDeclarado, tipoInscricaoTitular, inscricaoTitular, cpfBeneficiarioFinal, null);
        }
        
        /// <remarks/>
        public void ConsultarInformacoesRerctAsync(int idEventoRerct, string situacaoInformacao, string numeroRecibo, string cnpjDeclarante, string tipoInscricaoDeclarado, string inscricaoDeclarado, string tipoInscricaoTitular, string inscricaoTitular, string cpfBeneficiarioFinal, object userState) {
            if ((this.ConsultarInformacoesRerctOperationCompleted == null)) {
                this.ConsultarInformacoesRerctOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarInformacoesRerctOperationCompleted);
            }
            this.InvokeAsync("ConsultarInformacoesRerct", new object[] {
                        idEventoRerct,
                        situacaoInformacao,
                        numeroRecibo,
                        cnpjDeclarante,
                        tipoInscricaoDeclarado,
                        inscricaoDeclarado,
                        tipoInscricaoTitular,
                        inscricaoTitular,
                        cpfBeneficiarioFinal}, this.ConsultarInformacoesRerctOperationCompleted, userState);
        }
        
        private void OnConsultarInformacoesRerctOperationCompleted(object arg) {
            if ((this.ConsultarInformacoesRerctCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarInformacoesRerctCompleted(this, new ConsultarInformacoesRerctCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConsultarInformacoesCadastraisCompletedEventHandler(object sender, ConsultarInformacoesCadastraisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarInformacoesCadastraisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarInformacoesCadastraisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConsultarInformacoesIntermediarioCompletedEventHandler(object sender, ConsultarInformacoesIntermediarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarInformacoesIntermediarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarInformacoesIntermediarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConsultarInformacoesPatrocinadoCompletedEventHandler(object sender, ConsultarInformacoesPatrocinadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarInformacoesPatrocinadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarInformacoesPatrocinadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConsultarListaEFinanceiraCompletedEventHandler(object sender, ConsultarListaEFinanceiraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarListaEFinanceiraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarListaEFinanceiraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConsultarInformacoesMovimentoCompletedEventHandler(object sender, ConsultarInformacoesMovimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarInformacoesMovimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarInformacoesMovimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConsultarInformacoesRerctCompletedEventHandler(object sender, ConsultarInformacoesRerctCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarInformacoesRerctCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarInformacoesRerctCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591